"""Mutation-test `scripts/test_assignment.py`: the early-assignment fix (detect, value, unwind, alert).

Seeds real faults into a TEMP COPY of the repo (the real files are never edited) and demands the
suite catches every one. Engine: _mutate_repo_core.py.

Run: python scripts/mutate_assignment.py
"""
from __future__ import annotations

import sys

from _mutate_repo_core import run

MUTATIONS = [
    ('options_vrp/assignment.py',
     '        exact = (abs(qty - need) < 1e-9 and avg is not None',
     '        exact = (qty >= need and avg is not None',
     'quantity fingerprint loosened (blended position auto-sold)'),
    ('options_vrp/assignment.py',
     '                 and abs(float(avg) - float(sp.short_strike)) < 0.01)',
     '                 and True)',
     'price fingerprint dropped'),
    ('options_vrp/assignment.py',
     '        n = int(round(sp.contracts - max(short_held, 0.0)))',
     '        n = sp.contracts if short_held < sp.contracts else 0',
     'a partial assignment treated as full'),
    ('options_vrp/assignment.py',
     '    if put_actual is None or stock_detail is None:\n        return []\n',
     '',
     'unavailable positions treated as flat'),
    ('options_vrp/assignment.py',
     '        if getattr(sp, "assigned_contracts", 0):\n            continue                                   # already recorded',
     '        if False:\n            continue                                   # already recorded',
     'an assignment detected (and alerted) twice'),
    ('options_vrp/assignment.py',
     '            total += (sp.entry_credit + (s - sp.short_strike) + pl) * n_a',
     '            total += (sp.entry_credit + (s - sp.short_strike)) * n_a',
     'assigned value forgets the long put'),
    ('options_vrp/assignment.py',
     '            total += pl * n_a',
     '            total += (sp.entry_credit + pl) * n_a',
     'after the share sale the credit is counted twice'),
    ('options_vrp/assignment.py',
     '            if s is None:\n                return None',
     '            if s is None:\n                s = sp.short_strike',
     'a missing stock mark valued as if flat'),
    ('options_vrp/assignment.py',
     '    pnl = (sp.entry_credit + (price - sp.short_strike)) * mult * n',
     '    pnl = (price - sp.short_strike) * mult * n',
     'stock-leg P&L forgets the credit'),
    ('options_vrp/assignment.py',
     '        sp.contracts = remaining                   # the rest',
     '        sp.contracts = sp.contracts                # the rest',
     'partial unwind leaves the full contract count'),
    ('options_vrp/assignment.py',
     '    state.trade_log.append({"date": today, "action": "ASSIGNED", "key": a.key,',
     '    state.trade_log.append({"date": today, "action": "NOTE", "key": a.key,',
     'the ASSIGNED ledger row is not written'),
    ('scripts/run_options_paper.py',
     '            u = asg.unrealized(sp, put_marks, stock_marks)',
     '            u = None',
     'book_unrealized leaves ASSIGNED spreads out again'),
    ('scripts/run_options_paper.py',
     '        _unreal = book_unrealized(state, values, *broker.marks())',
     '        _unreal = 0.0',
     'circuit breaker blind to the book again'),
    ('scripts/run_options_paper.py',
     '        unreal = book_unrealized(state, values, *broker.marks())\n        state.record_snapshot',
     '        unreal = 0.0\n        state.record_snapshot',
     'NAV snapshot blind to the book again'),
    ('scripts/run_options_paper.py',
     '                continue\n            pnl = asg.book_stock_sale(state, sp, f["price"], today, f)',
     '                pass\n            pnl = 0.0 if f.get("price") is None else asg.book_stock_sale(state, sp, f["price"], today, f)',
     'long put sold although the share sale did not fill'),
    ('scripts/run_options_paper.py',
     '            if held is None or held < 100 * n:',
     '            if False:',
     'shares sold without checking they are held (opens a short)'),
    ('scripts/run_options_paper.py',
     '        if long_held is None or long_held < n:',
     '        if False:',
     'long put sold without checking it is held (writes a naked put)'),
    ('scripts/run_options_paper.py',
     '        if not sp.assigned_auto:',
     '        if False:',
     'a NOT-exact (blended) position is auto-unwound'),
    ('scripts/run_options_paper.py',
     '        if a.stock_qty >= a.shares_expected:\n            asg.mark_assigned',
     '        if a.exact:\n            asg.mark_assigned',
     'a blended assignment is not valued'),
    ('scripts/run_options_paper.py',
     '        logging.error("ASSIGNED %s: %s. Stock exposure ~%s. %s"',
     '        logging.info("ASSIGNED %s: %s. Stock exposure ~%s. %s"',
     'the same-day alert is below ERROR (never emailed)'),
    ('scripts/run_options_paper.py',
     '            if getattr(sp, "assigned_contracts", 0):\n                continue                                # ASSIGNED: handled by the unwind above\n',
     '',
     'the manage loop combo-closes a broken pair'),
    ('scripts/run_options_paper.py',
     '        orders.extend(handle_assignments(broker, state, today))\n',
     '',
     'run_live never handles assignments'),
    ('scripts/run_options_paper.py',
     '-float(sp.contracts - _n_a)',
     '-float(sp.contracts)',
     'reconcile raises a daily false PHANTOM for an assigned leg'),
    ('options_vrp/broker.py',
     '    def sell_stock(self, ticker: str, shares: float, label: str = "SAFETY: assignment unwind") -> dict:',
     '    def sell_stock(self, ticker: str, shares: float, label: str = "assignment unwind") -> dict:',
     'the share sale is not labelled SAFETY'),
    ('options_vrp/broker.py',
     '        if getattr(self, "order_ref", None):            # a missing tag must never stop an order\n            order.orderRef = self.order_ref\n        trade = self.ib.placeOrder(q[0], order)',
     '        trade = self.ib.placeOrder(q[0], order)',
     'unwind orders go out untagged'),
    ('options_vrp/broker.py',
     '            return {s: (q, (cost[s] / q) if q else None) for s, q in qty.items()}',
     '            return {s: (q, cost[s]) for s, q in qty.items()}',
     'average cost not per share (fingerprint never matches)'),
    ('options_vrp/broker.py',
     '        if self.dry_run:\n            logging.info("[DRY RUN] %s %s %g %s"',
     '        if False:\n            logging.info("[DRY RUN] %s %s %g %s"',
     'dry-run places real unwind orders'),
    ('scripts/run_options_paper.py',
     '        if long_held is not None and long_held <= 0:',
     '        if False:',
     'a hand-unwound assignment stays in state forever'),
    ('scripts/run_options_paper.py',
     '        if long_held is not None and long_held <= 0:',
     '        if not long_held:',
     "unavailable positions treated as 'unwound outside'"),
    ('scripts/run_options_paper.py',
     '        elif sp.key in values:\n            tot += (sp.entry_credit - values[sp.key]) * 100 * sp.contracts',
     '        elif False:\n            tot += (sp.entry_credit - values[sp.key]) * 100 * sp.contracts',
     'book_unrealized drops every INTACT spread'),
    ('scripts/run_options_paper.py',
     '                logging.warning("cannot value ASSIGNED %s (missing mark) — left out this run", sp.key)',
     '                pass',
     'an unvaluable assigned spread is dropped silently'),
    ('scripts/run_options_paper.py',
     '            logging.error("ASSIGNMENT UNWIND %s: long put sale NOT filled (%s); retry next run",\n                          sp.key, f2.get("status"))\n            continue',
     '            logging.error("ASSIGNMENT UNWIND %s: long put sale NOT filled (%s); retry next run",\n                          sp.key, f2.get("status"))\n            f2["price"] = 0.0',
     'an unfilled long-put sale is booked as sold'),
    ('options_vrp/broker.py',
     '                elif c.secType == "STK":\n                    stocks[c.symbol] = float(it.marketPrice)',
     '                elif False:\n                    stocks[c.symbol] = float(it.marketPrice)',
     'marks() returns no stock marks (assigned spreads unvaluable)'),
    ('options_vrp/broker.py',
     '                if c.secType == "OPT" and c.right == "P":\n                    puts[(c.symbol, c.lastTradeDateOrContractMonth, float(c.strike))] = float(it.marketPrice)',
     '                if c.secType == "OPT":\n                    puts[(c.symbol, c.lastTradeDateOrContractMonth, float(c.strike))] = float(it.marketPrice)',
     'marks() mixes calls into the put marks'),
    ('options_vrp/broker.py',
     '            logging.warning("%s: could not qualify %s", label, contract)\n            return {**base, "status": "qualify_failed"',
     '            logging.warning("%s: could not qualify %s", label, contract)\n            q = [contract]\n        if False:\n            return {**base, "status": "qualify_failed"',
     'an unqualifiable contract is ordered anyway'),
]

if __name__ == "__main__":
    sys.exit(run("test_assignment.py", MUTATIONS))
