"""Mutation-test `scripts/test_order_links.py`: the order -> IB record links (orderRef, execution ids, conid, commission, currency).

Seeds real faults into a TEMP COPY of the repo (the real files are never edited) and demands the
suite catches every one. Engine: _mutate_repo_core.py.

Run: python scripts/mutate_order_links.py
"""
from __future__ import annotations

import sys

from _mutate_repo_core import run

MUTATIONS = [
    ('options_vrp/broker.py',
     '        if getattr(self, "order_ref", None):            # a missing tag must never stop an order\n            order.orderRef = self.order_ref\n        trade = self.ib.placeOrder(bag, order)',
     '        trade = self.ib.placeOrder(bag, order)',
     'broker never stamps orderRef on the combo'),
    ('options_vrp/broker.py',
     '        if getattr(self, "order_ref", None):            # a missing tag must never stop an order\n            order.orderRef = self.order_ref\n        trade = self.ib.placeOrder(bag, order)',
     '        if self.order_ref:            # a missing tag must never stop an order\n            order.orderRef = self.order_ref\n        trade = self.ib.placeOrder(bag, order)',
     'a broker without a tag raises (a missing tag BLOCKS the trade)'),
    ('options_vrp/broker.py',
     'while not getattr(trade, "fills", None) and waited < wait:',
     'while not getattr(trade, "fills", None) and waited < 0:',
     "no wait for execution details that trail 'Filled'"),
    ('options_vrp/broker.py',
     'return [f.execution.execId for f in (getattr(trade, "fills", None) or [])]',
     'return [f.execution.execId for f in (getattr(trade, "fills", None) or [])][:1]',
     "only the combo's execution id kept, the legs' dropped"),
    ('options_vrp/broker.py',
     '                "exec_ids": ex, "order_ref": getattr(order, "orderRef", "") or "",\n                "conids": [int(getattr(short_leg',
     '                "exec_ids": ex, "order_ref": "",\n                "conids": [int(getattr(short_leg',
     'a fill drops its orderRef'),
    ('scripts/run_options_paper.py',
     '    b.order_ref = ORDER_REF\n',
     '',
     'RUNNER: make_broker never sets the tag'),
    ('scripts/run_options_paper.py',
     '    today = now.strftime("%Y-%m-%d")\n    broker = make_broker(port=',
     '    today = now.strftime("%Y-%m-%d")\n    from options_vrp.broker import OptionsBroker\n    broker = OptionsBroker(port=',
     'RUNNER: run_live bypasses make_broker (untagged broker)'),
    ('scripts/run_options_paper.py',
     'ORDER_REF = f"options-vrp:{RUN_ID}"',
     'ORDER_REF = f"vrp:{RUN_ID}"',
     'RUNNER: tag names the wrong strategy'),
    ('scripts/run_options_paper.py',
     '    state.record_open(sp, credit, today, order_ref=fill.get("order_ref", ""),\n                      exec_ids=fill.get("exec_ids"), conids=fill.get("conids"),',
     '    state.record_open(sp, credit, today, conids=fill.get("conids"),',
     'RUNNER: OPEN booked without tag or execution ids'),
    ('scripts/run_options_paper.py',
     'order_ref=fill.get("order_ref", ""),\n                                 exec_ids=fill.get("exec_ids"), conids=fill.get("conids"),',
     'conids=fill.get("conids"),',
     'RUNNER: CLOSE booked without tag or execution ids'),
    ('scripts/run_options_paper.py',
     '        state.pending_orders.append({"action": "open", "permId": fill.get("permId", 0),\n                                     "spread": asdict(sp), "placed_date": today,\n                                     "order_ref": fill.get("order_ref", "")})',
     '        state.pending_orders.append({"action": "open", "permId": fill.get("permId", 0),\n                                     "spread": asdict(sp), "placed_date": today})',
     'RUNNER: pending OPEN loses its orderRef'),
    ('scripts/run_options_paper.py',
     '    state.pending_orders.append({"action": "close", "permId": fill.get("permId", 0),\n                                 "spread": asdict(sp), "placed_date": today,\n                                 "order_ref": fill.get("order_ref", "")})',
     '    state.pending_orders.append({"action": "close", "permId": fill.get("permId", 0),\n                                 "spread": asdict(sp), "placed_date": today})',
     'RUNNER: pending CLOSE loses its orderRef'),
    ('scripts/run_options_paper.py',
     '    if fill["status"] == "Filled" and fill["net_price"] is not None:\n        pnl',
     '    if fill["net_price"] is not None:\n        pnl',
     'RUNNER: an unfilled CLOSE is booked (the phantom-close bug)'),
    ('scripts/run_options_paper.py',
     '                    order_ref=p.get("order_ref", ""))\n',
     '                    )\n',
     'SELF-HEAL: late CLOSE booked without its orderRef'),
    ('scripts/run_options_paper.py',
     'state.record_open(sp, float(credit), today, order_ref=p.get("order_ref", ""))',
     'state.record_open(sp, float(credit), today)',
     'SELF-HEAL: late OPEN booked without its orderRef'),
    ('scripts/run_options_paper.py',
     '                if book_open(state, sp, fill, s.credit, today):',
     '                if False:',
     'RUNNER: run_live stops booking opens'),
    ('options_vrp/state.py',
     '"order_ref": order_ref, "exec_ids": list(exec_ids or []),\n                               "conids": list(conids or []), "commission": commission,\n                               "currency": currency})\n\n    def record_close',
     '"order_ref": order_ref, "exec_ids": [],\n                               "conids": list(conids or []), "commission": commission,\n                               "currency": currency})\n\n    def record_close',
     'trade_log OPEN drops the execution ids'),
    ('options_vrp/broker.py',
     '                "conids": [int(getattr(short_leg, "conId", 0) or 0), int(getattr(long_leg, "conId", 0) or 0)],',
     '                "conids": [int(getattr(long_leg, "conId", 0) or 0), int(getattr(short_leg, "conId", 0) or 0)],',
     'leg conids recorded in the wrong order'),
    ('options_vrp/broker.py',
     '                "commission": self._commission(trade) if st == "Filled" else None,\n                "currency": "USD"}',
     '                "commission": None,\n                "currency": "USD"}',
     'combo commission never recorded'),
    ('options_vrp/broker.py',
     '                if fills and all(r is not None and getattr(r, "execId", "") for r in reps):',
     '                if fills:',
     'commission reports counted before IB sent them'),
    ('scripts/run_options_paper.py',
     '                      exec_ids=fill.get("exec_ids"), conids=fill.get("conids"),\n                      commission=fill.get("commission"), currency=fill.get("currency") or "")',
     '                      exec_ids=fill.get("exec_ids"))',
     'book_open drops conids/commission/currency'),
]

if __name__ == "__main__":
    sys.exit(run("test_order_links.py", MUTATIONS))
